/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.taller2pa.vista;

/**
 *
 * @author Juan Carlos Rojas
 */
public class SeleccionJugadoresView extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionJugadoresView
     */
    public SeleccionJugadoresView() {
        initComponents();
        this.setSize(800, 600); // O el tamaño que tú quieres
this.setLocationRelativeTo(null); // Para que la ventana aparezca centrada

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCrupier = new javax.swing.JLabel();
        panelJugador2 = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        btnPedirCarta = new javax.swing.JButton();
        btnPlantarse = new javax.swing.JButton();
        btnDoblarApuesta = new javax.swing.JButton();
        lblDatosJugador1 = new javax.swing.JLabel();
        lblDatosJugador2 = new javax.swing.JLabel();
        panelCrupier = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondoMesa = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionar Jugadores y Crupier");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCrupier.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblCrupier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrupier.setText("Crupier");
        getContentPane().add(lblCrupier, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 138, -1));

        panelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        panelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        btnPedirCarta.setBackground(new java.awt.Color(255, 215, 0));
        btnPedirCarta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedirCarta.setText("Pedir carta");
        btnPedirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirCartaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedirCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        btnPlantarse.setBackground(new java.awt.Color(255, 215, 0));
        btnPlantarse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPlantarse.setText("Plantarse");
        getContentPane().add(btnPlantarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        btnDoblarApuesta.setBackground(new java.awt.Color(255, 215, 0));
        btnDoblarApuesta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDoblarApuesta.setText("Doblar apuesta");
        getContentPane().add(btnDoblarApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        lblDatosJugador1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblDatosJugador1.setText("Apuesta: 0 | Dinero: 1000 ");
        getContentPane().add(lblDatosJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblDatosJugador2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblDatosJugador2.setText("Apuesta: 0 | Dinero: 1000 ");
        getContentPane().add(lblDatosJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        panelCrupier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelCrupierLayout = new javax.swing.GroupLayout(panelCrupier);
        panelCrupier.setLayout(panelCrupierLayout);
        panelCrupierLayout.setHorizontalGroup(
            panelCrupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelCrupierLayout.setVerticalGroup(
            panelCrupierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(panelCrupier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Carlos Rojas\\Downloads\\TallerBlackJack\\src\\main\\resources\\img\\fichaCasino.png.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 50, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Carlos Rojas\\Downloads\\TallerBlackJack\\src\\main\\resources\\img\\fichaCasino.png.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 50, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Carlos Rojas\\Downloads\\TallerBlackJack\\src\\main\\resources\\img\\cartasCentro.png.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, 80));

        fondoMesa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Juan Carlos Rojas\\Downloads\\TallerBlackJack\\src\\main\\resources\\img\\mesaBlacjack.png.png")); // NOI18N
        fondoMesa.setText("jLabel2");
        getContentPane().add(fondoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedirCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionJugadoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoblarApuesta;
    private javax.swing.JButton btnPedirCarta;
    private javax.swing.JButton btnPlantarse;
    private javax.swing.JLabel fondoMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCrupier;
    private javax.swing.JLabel lblDatosJugador1;
    private javax.swing.JLabel lblDatosJugador2;
    private javax.swing.JPanel panelCrupier;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    // End of variables declaration//GEN-END:variables
}
