/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.taller2pa.vista;

/**
 *
 * @author Juan Carlos Rojas
 */

import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.Image;

public class ApuestaView extends javax.swing.JFrame {

    
    
    /**
     * Creates new form ApuestaView
     */
    public ApuestaView() {
        initComponents();
        ponerIcono(btnFicha10Jugador1, "/img/ficha1.png");
        ponerIcono(btnFicha50Jugador1, "/img/ficha2.png");
ponerIcono(btnFicha100Jugador1, "/img/ficha3.png");
ponerIcono(btnFicha10Jugador2, "/img/ficha1.png");
ponerIcono(btnFicha50Jugador2, "/img/ficha2.png");
ponerIcono(btnFicha100Jugador2, "/img/ficha3.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJugador1 = new javax.swing.JPanel();
        lblNombreJugador2 = new javax.swing.JLabel();
        btnFicha10Jugador2 = new javax.swing.JButton();
        btnFicha50Jugador2 = new javax.swing.JButton();
        btnFicha100Jugador2 = new javax.swing.JButton();
        lblFichasJugador2 = new javax.swing.JLabel();
        lblDineroJugador2 = new javax.swing.JLabel();
        btnListoJugador2 = new javax.swing.JButton();
        panelJugador2 = new javax.swing.JPanel();
        lblNombreJugador1 = new javax.swing.JLabel();
        btnFicha10Jugador1 = new javax.swing.JButton();
        btnFicha50Jugador1 = new javax.swing.JButton();
        btnFicha100Jugador1 = new javax.swing.JButton();
        lblFichasJugador1 = new javax.swing.JLabel();
        lblDineroJugador1 = new javax.swing.JLabel();
        btnListoJugador1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apuestas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJugador1.setBackground(new java.awt.Color(200, 230, 255));

        lblNombreJugador2.setText("Jugador 2");

        btnFicha10Jugador2.setBackground(new java.awt.Color(182, 227, 136));
        btnFicha10Jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha1.png"))); // NOI18N
        btnFicha10Jugador2.setPreferredSize(new java.awt.Dimension(60, 60));

        btnFicha50Jugador2.setBackground(new java.awt.Color(136, 196, 227));
        btnFicha50Jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha2.png"))); // NOI18N
        btnFicha50Jugador2.setPreferredSize(new java.awt.Dimension(60, 60));

        btnFicha100Jugador2.setBackground(new java.awt.Color(227, 136, 136));
        btnFicha100Jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha3.png"))); // NOI18N
        btnFicha100Jugador2.setPreferredSize(new java.awt.Dimension(60, 60));
        btnFicha100Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha100Jugador2ActionPerformed(evt);
            }
        });

        lblFichasJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFichasJugador2.setText("Fichas: 0");

        lblDineroJugador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroJugador2.setText("Dinero: 1000");

        btnListoJugador2.setBackground(new java.awt.Color(241, 194, 50));
        btnListoJugador2.setText("Listo");

        javax.swing.GroupLayout panelJugador1Layout = new javax.swing.GroupLayout(panelJugador1);
        panelJugador1.setLayout(panelJugador1Layout);
        panelJugador1Layout.setHorizontalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJugador1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFichasJugador2)
                    .addGroup(panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnFicha100Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFicha10Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreJugador2)
                        .addComponent(btnFicha50Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDineroJugador2))
                    .addComponent(btnListoJugador2))
                .addGap(113, 113, 113))
        );
        panelJugador1Layout.setVerticalGroup(
            panelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNombreJugador2)
                .addGap(46, 46, 46)
                .addComponent(btnFicha10Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnFicha50Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnFicha100Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblFichasJugador2)
                .addGap(18, 18, 18)
                .addComponent(lblDineroJugador2)
                .addGap(18, 18, 18)
                .addComponent(btnListoJugador2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 300, 480));

        panelJugador2.setBackground(new java.awt.Color(200, 255, 200));
        panelJugador2.setToolTipText("");

        lblNombreJugador1.setText("Jugador 1");

        btnFicha10Jugador1.setBackground(new java.awt.Color(182, 227, 136));
        btnFicha10Jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha1.png"))); // NOI18N
        btnFicha10Jugador1.setPreferredSize(new java.awt.Dimension(60, 60));
        btnFicha10Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha10Jugador1ActionPerformed(evt);
            }
        });

        btnFicha50Jugador1.setBackground(new java.awt.Color(136, 196, 227));
        btnFicha50Jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha2.png"))); // NOI18N
        btnFicha50Jugador1.setPreferredSize(new java.awt.Dimension(60, 60));
        btnFicha50Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha50Jugador1ActionPerformed(evt);
            }
        });

        btnFicha100Jugador1.setBackground(new java.awt.Color(227, 136, 136));
        btnFicha100Jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ficha3.png"))); // NOI18N
        btnFicha100Jugador1.setPreferredSize(new java.awt.Dimension(60, 60));
        btnFicha100Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha100Jugador1ActionPerformed(evt);
            }
        });

        lblFichasJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFichasJugador1.setText("Fichas: 0");

        lblDineroJugador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDineroJugador1.setText("Dinero: 1000");

        btnListoJugador1.setBackground(new java.awt.Color(241, 194, 50));
        btnListoJugador1.setText("Listo");

        javax.swing.GroupLayout panelJugador2Layout = new javax.swing.GroupLayout(panelJugador2);
        panelJugador2.setLayout(panelJugador2Layout);
        panelJugador2Layout.setHorizontalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelJugador2Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(lblFichasJugador1))
                        .addGroup(panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFicha100Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFicha50Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFicha10Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreJugador1)
                            .addComponent(lblDineroJugador1)))
                    .addComponent(btnListoJugador1))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panelJugador2Layout.setVerticalGroup(
            panelJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugador2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNombreJugador1)
                .addGap(43, 43, 43)
                .addComponent(btnFicha10Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnFicha50Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnFicha100Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblFichasJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDineroJugador1)
                .addGap(18, 18, 18)
                .addComponent(btnListoJugador1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFicha50Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha50Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFicha50Jugador1ActionPerformed

    private void btnFicha100Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha100Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFicha100Jugador2ActionPerformed

    private void btnFicha10Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha10Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFicha10Jugador1ActionPerformed

    private void btnFicha100Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha100Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFicha100Jugador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApuestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApuestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApuestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApuestaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApuestaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFicha100Jugador1;
    private javax.swing.JButton btnFicha100Jugador2;
    private javax.swing.JButton btnFicha10Jugador1;
    private javax.swing.JButton btnFicha10Jugador2;
    private javax.swing.JButton btnFicha50Jugador1;
    private javax.swing.JButton btnFicha50Jugador2;
    private javax.swing.JButton btnListoJugador1;
    private javax.swing.JButton btnListoJugador2;
    private javax.swing.JLabel lblDineroJugador1;
    private javax.swing.JLabel lblDineroJugador2;
    private javax.swing.JLabel lblFichasJugador1;
    private javax.swing.JLabel lblFichasJugador2;
    private javax.swing.JLabel lblNombreJugador1;
    private javax.swing.JLabel lblNombreJugador2;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    // End of variables declaration//GEN-END:variables
private void ponerIcono(JButton boton, String rutaImagen) {
    ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
    Image imagenEscalada = icono.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    boton.setIcon(new ImageIcon(imagenEscalada));
    boton.setText("");
    boton.setBorderPainted(false);
    boton.setContentAreaFilled(false);
}


}

